name: Cache Envs from Azure KeyVault

description: Generates and caches a env file

inputs:
  azurecredentials:
    description: "Credentials to login to Azure"
    required: true
  environmentKeyVault:
    description: "Azure Key Vault Name"
    required: false
  repositoryName:
    required: false
    description: "GitHub Repository Name."
    default: ${{ github.event.repository.name }}
  environment:
    required: false
    description: "Deployment environment"

branding:
  color: purple
  icon: unlock
runs:
  using: "composite"
  steps:
    - name: Hash azurecredentials secret
      uses: pplanel/hash-calculator-action@v1.3.1
      id: hash
      with:
        input: ${{ secrets.azurecredentials }}
        method: MD5

    - name: Cache Azure credentials
      id: azure-cache
      uses: actions/cache@v3
      with:
        path: ~/.azure
        key: ${{ runner.os }}-azurecreds-${{ steps.hash.outputs.digest }}

    - name: Login via Az module
      if: steps.azure-cache.outputs.cache-hit != 'true'
      uses: azure/login@v1
      with:
        creds: "${{ secrets.azurecredentials }}"
        enable-AzPSSession: true

    - name: Generate .env file from Azure Key Vaults
      uses: azure/powershell@v1.2.0
      with:
        inlineScript: |
          $environment = "${{ inputs.environment }}"
          $repositoryName = "${{ inputs.repositoryName }}"

          if ("${{ inputs.environmentKeyVault }}") {
              $KeyVaultName = "${{ inputs.environmentKeyVault }}"
          }
          else {
              $KeyVaultName = (Get-AzKeyVault -Tag @{"environment" = "$environment" } | Get-AzKeyVault -Tag @{"repository-name" = "$repositoryName" }).VaultName
          }

          [String]$KeyVaultName = $KeyVaultName.Replace(" ", "")
          Write-Output "::notice::KeyVaultName: $KeyVaultName"
          $envSecrets = (Get-AzKeyVaultSecret -VaultName $KeyVaultName  | Where-Object { ($_.ContentType -contains 'Env') -or ($_.ContentType -contains 'BuildArg Env') }).Name
          if ($envSecrets) {
            $envSecrets | ForEach-Object {
                $envName = $_.ToUpper().Replace("-", "_")
                $envSecret = (Get-AzKeyVaultSecret -VaultName $KeyVaultName -Name $_).secretvalue | ConvertFrom-SecureString -AsPlainText
                $envContent = $envName + "=" + $envSecret
                Add-Content -Path "${{ github.workspace }}/.env" -Value $envContent
            }
          }
          else {
            Add-Content -Path "${{ github.workspace }}/.env" ""
          }
        azPSVersion: "latest"

    - name: Source secrets file
      shell: sh
      run: |
        while read -r envVar; do
            if [ $(echo "${envVar}" | grep -Ei "SECRET|TOKEN|KEY|PASS|CONNECTION_STRING") ]; then
              VAR=$(echo "${envVar}" | awk -F '=' '{print $1}')
              VALUE=$(echo $envVar | sed "s/$VAR=//g")
              echo "::add-mask::$VALUE"
            fi
            echo "$envVar" >> $GITHUB_ENV
        done < ${{ github.workspace }}/.env
