name: Add PR Labels

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, development]

jobs:
  codeowners-validation:
    name: Codeowners File Validation
    uses: Andrews-McMeel-Universal/reusable_workflows/.github/workflows/pr-labels.yaml@2.2.0
    secrets:
      PAT_ACTION_CI: ${{ secrets.PAT_ACTION_CI }}
